OdeToFood/odeToFood/Pages/About.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace odeToFood.Pages
{
    public class AboutModel : PageModel
    {
        public string Message { get; set; }

        public void OnGet()
        {
            Message = "Your application description page.";
        }
    }
}

OdeToFood/odeToFood/Pages/Contact.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace odeToFood.Pages
{
    public class ContactModel : PageModel
    {
        public string Message { get; set; }

        public void OnGet()
        {
            Message = "Your contact page.";
        }
    }
}

OdeToFood/odeToFood/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace odeToFood.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

OdeToFood/odeToFood/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace odeToFood.Pages
{
    public class IndexModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

OdeToFood/odeToFood/Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace odeToFood.Pages
{
    public class PrivacyModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

OdeToFood/odeToFood/Pages/Resturants/ClientResturants.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace odeToFood.Pages.Resturants
{
    public class ClientResturantsModel : PageModel
    {
        
    }
}

OdeToFood/odeToFood/Pages/Resturants/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using OdeToFood.Core;
using OdeToFood.Data;

namespace odeToFood.Pages.Resturants
{
    public class DeleteModel : PageModel
    {
        public Resturant Resturant { get; set; }
        private readonly IResturantData resturantData;

        public DeleteModel(IResturantData resturantData)
        {
            this.resturantData = resturantData;
        }
        public IActionResult OnGet(int resturantId)
        {
            Resturant = resturantData.getById(resturantId);
            if(Resturant == null)
            {
                return RedirectToPage("./NotFound");
            }
            return Page();
        }

        public IActionResult OnPost(int resturantId)
        {
            Resturant resturant = resturantData.delete(resturantId);
            if (resturant == null)
            {
                return RedirectToPage("./NotFound");
            }

            TempData["message"] = $"{resturant.Name} deleted";
            return RedirectToPage("./List");
        }
    }
}

OdeToFood/odeToFood/Pages/Resturants/Detail.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using OdeToFood.Core;
using OdeToFood.Data;

namespace odeToFood.Pages.Resturants
{
    public class DetailModel : PageModel
    {
        private readonly IResturantData resturantData;

        public Resturant Resturant { get; set; }
        [TempData]
        public string Message { get; set; }
        public DetailModel(IResturantData resturantData)
        {
            this.resturantData = resturantData;
        }
        public IActionResult OnGet(int resturantId)
        {
            Resturant = resturantData.getById(resturantId);
            if (Resturant == null)
            {
                return RedirectToPage("./NotFound");
            }

            return Page();
        }
    }
}

OdeToFood/odeToFood/Pages/Resturants/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using OdeToFood.Core;
using OdeToFood.Data;

namespace odeToFood.Pages.Resturants
{
    public class EditModel : PageModel
    {
        private readonly IResturantData resturantData;
        private readonly IHtmlHelper htmlHelper;
        [BindProperty]
        public Resturant Resturant { get; set; }
        public IEnumerable<SelectListItem> Cuisines { get; set; }
        public EditModel(IResturantData resturantData, IHtmlHelper htmlHelper)
        {
            this.resturantData = resturantData;
            this.htmlHelper = htmlHelper;
        }
        public IActionResult OnGet(int? resturantId)
        {
            Cuisines = htmlHelper.GetEnumSelectList<CuisineType>();
            if (resturantId.HasValue)
                Resturant = resturantData.getById(resturantId.Value);
            else
                Resturant = new Resturant();

            return Page();
        }

        public IActionResult OnPost()
        {
            if (!ModelState.IsValid)
            {
                Cuisines = htmlHelper.GetEnumSelectList<CuisineType>();
                return Page();
            }

            if (Resturant.Id > 0)
                resturantData.update(Resturant);
            else
                resturantData.Add(Resturant);
            TempData["Message"] = "Saved Successfully";
            return RedirectToPage("./Detail", new { resturantId = Resturant.Id });

        }
    }
}

OdeToFood/odeToFood/Pages/Resturants/List.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using OdeToFood.Core;
using OdeToFood.Data;

namespace odeToFood.Pages.Resturants
{
    public class ListModel : PageModel
    {
        private readonly IConfiguration config;
        private readonly IResturantData resturantData;
        private readonly ILogger<ListModel> logger;

        public IEnumerable<Resturant> Resturants { get; set; }
        [BindProperty(SupportsGet = true)]
        public string SearchTerm { get; set; }
        public ListModel(IConfiguration config, IResturantData resturantData, ILogger<ListModel> logger)
        {
            this.config = config;
            this.resturantData = resturantData;
            this.logger = logger;
        }
        public string Message { get; set; }

        public void OnGet()
        {
            logger.LogError("Executing Resturant list");
            Message = config["Message"];
            Resturants = resturantData.GetResturantsByName(SearchTerm);
        }
    }
}

OdeToFood/odeToFood/Pages/ViewComponts/ResturantCountViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using OdeToFood.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace odeToFood.Pages.ViewComponts
{
    public class ResturantCountViewComponent : ViewComponent
    {
        private readonly IResturantData resturantdata;

        public ResturantCountViewComponent(IResturantData resturantdata)
        {
            this.resturantdata = resturantdata;
        }

        public IViewComponentResult Invoke()
        {
            var count = resturantdata.getResturantCount();

            return View(count);
        }
    }
}

OdeToFood/odeToFood/Pages/About.cshtml
@page
@model AboutModel
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@Model.Message</h3>

<p>Hello This is anand</p>

OdeToFood/odeToFood/Pages/Contact.cshtml
@page
@model ContactModel
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@Model.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

OdeToFood/odeToFood/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core Razor Pages</li>
            <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?linkid=852130">Working with Razor Pages.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run &amp; Deploy</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure App Service</a></li>
        </ul>
    </div>
</div>

OdeToFood/odeToFood/Pages/Resturants/ClientResturants.cshtml
@page
@model odeToFood.Pages.Resturants.ClientResturantsModel
@{
    ViewData["Title"] = "ClientResturants";
}

<h2>Client Resturants</h2>

@section scripts {

    <environment include="Development">
        <link rel="stylesheet" type="text/css" href="/DataTables/datatables.css" />
        <script type="text/javascript" charset="utf8" src="/DataTables/datatables.js"></script>
    </environment>

    <environment exclude="Development">
        <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.css" />
        <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.js"></script>
    </environment>

    <script>
        $(function () {
            $.ajax("/api/resturants")
                .then(function (response) {
                    console.dir(response);
                })
        })

    </script>
}

OdeToFood/odeToFood/Pages/Resturants/Delete.cshtml
@page "{resturantId:int}"
@model odeToFood.Pages.Resturants.DeleteModel
@{
    
}

<h2>Delete</h2>
<div class="alert alert-danger">
    Are you sure want to delete @Model.Resturant.Name
</div>

<form  method="post">
    <button type="submit" class="btn btn-danger">Yes!</button>
    <a asp-page="List" class="btn btn-default"> Cancel </a>
</form>

OdeToFood/odeToFood/Pages/Resturants/Detail.cshtml
@page "{resturantId:int}"

@model odeToFood.Pages.Resturants.DetailModel
@{
    ViewData["Title"] = "Detail";
}

<h2>Resturant Detail</h2>
@if(Model.Message !=null)
{
    <div class="alert alert-info">@Model.Message</div>
}

<div>
    Id : @Model.Resturant.Id
</div>
<div>
    Name : @Model.Resturant.Name
</div>
<div>
    Location : @Model.Resturant.Location
</div>
<div>
    Cuisine : @Model.Resturant.Cuisine
</div>

<a asp-page="./List" class="btn btn-default">All Resturarents</a>

OdeToFood/odeToFood/Pages/Resturants/Edit.cshtml
@page "{resturantId:int?}"
@model odeToFood.Pages.Resturants.EditModel
@{
    ViewData["Title"] = "Edit";
}

<h2>You are editing @Model.Resturant.Name</h2>

<form method="post">
    <input type="hidden" asp-for="Resturant.Id" />
    <div class="form-group">
        <label asp-for="Resturant.Name"></label>
        <input asp-for="Resturant.Name" class="form-control" />
        <span class="text-danger" asp-validation-for="Resturant.Name"></span>
    </div>

    <div class="form-group">
        <label asp-for="Resturant.Location"></label>
        <input asp-for="Resturant.Location" class="form-control" />
        <span class="text-danger" asp-validation-for="Resturant.Location"></span>
    </div>

    <div class="form-group">
        <label asp-for="Resturant.Cuisine"></label>
        <select class="form-control" asp-for="Resturant.Cuisine" asp-items="Model.Cuisines">
        </select>
    </div>

    <button type="submit" , class="btn btn-primary">Save</button>
</form>
@section scripts {
    <partial name="_ValidationScriptsPartial"></partial>
}

OdeToFood/odeToFood/Pages/Resturants/List.cshtml
@page
@model ListModel
@{
}
<h1>Resturants</h1>

<form method="get">
    <div class="form-group">
        <div class="input-group">
            <input type="search" class="form-control" asp-for="SearchTerm"/>
            <span class=" input-group-btn">
                <button class="btn btn-default">
                    <i class="glyphicon glyphicon-search"></i>
                </button>
            </span>
        </div>
    </div>
</form>


@foreach (var resturant in Model.Resturants)
{
    <partial name="_Summary" model="resturant" />
}

<a asp-page="./Edit" class="btn btn-primary">Add New Resturant</a>


<div>@Model.Message</div>

OdeToFood/odeToFood/Pages/Resturants/NotFound.cshtml
@page
@{
    ViewData["Title"] = "NotFound";
}

<h2>Your Resturant was not found</h2>

<a asp-page="./List" class="btn btn-primary">All Resturants</a>

OdeToFood/odeToFood/Pages/Resturants/_Summary.cshtml
@using OdeToFood.Core
@Model Resturant

<div class="panel panel-default">
    <div class="panel-heading">
        <h3>@Model.Name</h3>
    </div>

    <div class="panel-body">
        <span>Location: @Model.Location</span>
        <span>Cuisine: @Model.Cuisine</span>
    </div>

    <div class="panel-footer">
        <a asp-page="./Detail" asp-route-resturantId="@Model.Id" class="btn btn-lg">
            <i class="glyphicon glyphicon-zoom-in"></i>
        </a>
        <a asp-page="./Edit" asp-route-resturantId="@Model.Id" class="btn btn-lg">
            <i class="glyphicon glyphicon-edit"></i>
        </a>
        <a asp-page="./Delete" asp-route-resturantId="@Model.Id" class="btn btn-lg">
            <i class="glyphicon glyphicon-trash"></i>
        </a>
    </div>

</div>

OdeToFood/odeToFood/Pages/Shared/Components/ResturantCount/Default.cshtml
@model int

    <div class=" well">
        There are @Model resturants are here. <a asp-page="/Resturants/List">See Them All</a>
    </div>

OdeToFood/odeToFood/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - odeToFood</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-page="/Index" class="navbar-brand">odeToFood</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-page="/Index">Home</a></li>
                    <li><a asp-page="/Resturants/List">Resturants</a></li>
                    <li><a asp-page="/About">About</a></li>
                    <li><a asp-page="/Contact">Contact</a></li>
                    <li><a asp-page="/test/test1">test</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <vc:resturant-count></vc:resturant-count>
            <p>&copy; 2019 - odeToFood</p>
            <img src="~/OdeToFood.png" alt="Ode to food" />
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>